modified:   jpf-core-sv-comp: Updates from Yannic.

diff --git a/bin/jpf-core-sv-comp b/bin/jpf-core-sv-comp
--- a/bin/jpf-core-sv-comp
+++ b/bin/jpf-core-sv-comp
@@ -5,61 +5,60 @@
 
 # create site.properties
 SITE_PROPERTIES=site.properties
-P="`dirname $0`"
-echo "jpf-core = $P/.." > $SITE_PROPERTIES
+echo "jpf-core = `pwd`/jpf-core" > $SITE_PROPERTIES
 echo "extensions=\${jpf-core}" >> $SITE_PROPERTIES
 
 # parse arguments
-BENCHMARK=""
-PROPERTY_FILE=""
+declare -a BM
+BM=()
+PROP_FILE=""
 WITNESS_FILE=""
+
+TOOL_BINARY=jpf-core/bin/jpf
+FIND_OPTIONS="-name '*.java'"
 
 while [ -n "$1" ] ; do
   case "$1" in
-    --propertyfile) PROPERTY_FILE="$2" ; shift 2 ;;
+    --32|--64) BIT_WIDTH="${1##--}" ; shift 1 ;;
+    --propertyfile) PROP_FILE="$2" ; shift 2 ;;
     --graphml-witness) WITNESS_FILE="$2" ; shift 2 ;;
-    --version) "$P/bin/jpf" -version ; exit 0 ;;
-    *) BENCHMARK="$1" ; shift 1 ;;
+    --version) $TOOL_BINARY -version ; exit 0 ;;
+    *) SRC=(`eval "find $1 $FIND_OPTIONS"`) ; BM=("${BM[@]}" "${SRC[@]}") ; shift 1 ;;
   esac
 done
 
-if [ -z "$BENCHMARK" ] ; then
-  echo "Missing benchmark file"
+if [ -z "${BM[0]}" ] || [ -z "$PROP_FILE" ] ; then
+  echo "Missing benchmark or property file"
   exit 1
 fi
 
-if [ -z "$PROPERTY_FILE" ] ; then
-  echo "Missing property file"
+if [ ! -s "${BM[0]}" ] || [ ! -s "$PROP_FILE" ] ; then
+  echo "Empty benchmark or property file"
   exit 1
 fi
-
-if [ ! -s "$BENCHMARK" ]  ; then
-  echo "Empty benchmark file"
-  exit 1
-fi
-
-if [ ! -s "$PROPERTY_FILE" ] ; then
-  echo "Empty property file"
-  exit 1
-fi
-
-LOG=`mktemp -t jpf-log.XXXXXX`
-DIR=`mktemp -d -t jpf-benchmark.XXXXXX`
-trap "rm -rf $DIR $LOG" EXIT
 
 # we ignore the property file (there is only one property at the moment)
 # we ignore the witness file (not used yet)
-# we unpack the benchmark zip file, build it and analyze it
-unzip $BENCHMARK -d $DIR
-make -C $DIR
+
+LOG=`mktemp -t jpf-log.XXXXXX`
+DIR=`mktemp -d -t jpf-benchmark.XXXXXX`
+trap "rm -rf $DIR" EXIT
+
+# create target directory
+mkdir -p $DIR/target/classes
+
+# build src files from benchmark
+javac -g -cp $DIR/target/classes -d $DIR/target/classes "${BM[@]}"
 
 # create configuration file
 echo "target=Main" > $DIR/config.jpf
 echo "classpath=$DIR/target/classes" >> $DIR/config.jpf
 echo "cg.enumerate_random=true" >> $DIR/config.jpf
 
-"$P/bin/jpf" $DIR/config.jpf +cg.enumerate_random | tee $LOG
+# run JPF
+jpf-core/bin/jpf $DIR/config.jpf +cg.enumerate_random | tee $LOG
 
+# check the result
 grep "no errors detected" $LOG > /dev/null
 if [ $? -eq 0 ]; then
   echo "SAFE"
